export const SUCCESS_CODE = 0;
export const ERROR = {
  AUTH: {
    MISSING_EMAIL: 1,
    MISSING_PASSWORD: 2,
    INVALID_EMAIL: 3,
    WEAK_PASSWORD: 4,
    NOT_REGISTER_YET: 5,
    MISSING_NAME: 6,
    EMAIL_ALREADY_EXIST: 7,
    INCORRECT_PASSWORD: 9,
    MISSING_PHONE: 10,
    PHONE_ALREADY_EXIST: 11,
  },
  CONVERSATION: {
    MISSING_CONTACT_ID: 12,
  },
  CONTACT: {
    MISSING_USER_ID: 13,
  },
  MESSAGE: {
    CANNOT_SEND_EMPTY_BODY: 14,
    MUST_HAVE_RECEIVER: 15,
    MUST_HAVE_SENDER: 16,
    SOME_ERROR_HAPPENED: 17,
  },
};
